/**:
  ros__parameters:
    use_sim_time: true

robot_state_publisher:
  ros__parameters:
    publish_frequency: 50.0

# Add more parameters for different nodes
gazebo:
  ros__parameters:
    world_file: "worlds/diff_drive/diff_drive.sdf"
    use_gui: true
    robot_name: "simple_robot"
    spawn_position:
      x: 0.0
      y: 0.0
      z: 0.1

teleop_twist_keyboard:
  ros__parameters:
    cmd_vel_topic: "/cmd_vel"