/**:
  ros__parameters:
    use_sim_time: true

robot_state_publisher:
  ros__parameters:
    publish_frequency: 50.0

# Add more parameters for different nodes

robot_state_publisher_node:
  ros__parameters:
    use_sim_time: true
    qos_overrides:
      /robot_description.publisher:
        durability: transient_local
        reliability: reliable 

rviz_node:
  ros__parameters:
    use_sim_time: true